[knife]
hnsru_arena 

[skill]
; map_name roundtime freezetime flash smoke

; --- hns_ ---
c21_kitty_end 3.2 5 1 1
c21_clr 3.5 5 1 1
c21_ girs 3.5 5 1 1
c21_pink 3.2 5 1 1
c21_fruitcake_b2 3.5 5 1 1
hns_assault_duel 2.5 5 1 1
hns_assault_rmk02 2.5 5 1 1
hns_bounce 2.5 5 1 1
hns_briktown 2.5 5 1 1
hns_concreto 2.7 5 1 1
hns_cccp2 3.5 5 2 1
hns_definition 2.5 5 1 1
hns_desolate 2.5 5 1 1
hns_dust 2.5 5 1 1
hns_dust2 2.5 5 1 1
hns_egypt_fix 2.5 5 1 1
hns_earthward 2.5 5 1 1
hns_hale 3.0 5 2 1 
hns_nightlife 3.0 5 2 1
hns_floppytown 2.5 5 1 1
hns_floppytown_mnx 2.5 5 1 1
hns_floppytown_pro_winter 3.0 5 1 1
hnscn_floppytown_b2 3.0 5 1 1
hns_forever_uctt_v2 2.5 5 2 1
hns_lostcanyon 2.5 5 1 1
hns_monkeys01 2.5 5 0 1
hns_oldtown 2.5 5 1 1
hns_tyo 3.0 5 1 1
hns_skatepark 2.5 5 1 1
hns_virtual 2.5 5 1 1
hns_village_final3 2.5 5 1 1
hns_weekend 3.2 5 1 1
de_dust2_hns 2.5 5 1 1
hns_dust2 3.5 5 1 1 
hns_dust 3.5 5 1 1
hns_proworld 3.5 5 1 1
hns_proworld_remake 3.5 5 1 1
hns_egypt_fix 3.0 5 1 1
; --- hnsru_ ---
hnsru_assens01 2.5 5 1 1
hnsru_hell01 2.5 5 1 1
hnsru_sliders01 2.5 5 1 1


;---hnsbg---
hnsbg_celtic 3.0 5 1 1

;---hnscn---
hnscn_plaka_b1 3.0 5 1 1

; --- huyarish_ ---
huyarish_rooftops 2.5 5 1 1

; --- rayish_ ---
rayish_backyard 2.5 5 1 1
rayish_brick-world 2.5 5 1 1
rayish_hell 2.5 5 1 1
rayish_ruins 2.5 5 1 1
rayish_saxum 2.5 5 1 1
rayish_survival 2.5 5 2 1
rayish_sunset 2.5 5 1 1
rayish_town 2.5 5 1 1
rayish_trickpark 2.5 5 1 1

; --- ankh_ ---
ankh_morpork 2.5 5 1 1

[boost]
; map_name roundtime freezetime flash smoke

; --- 5A_ ---
mansion02 3.5 15 3 1
5A_cross 3.5 15 3 1
5A_cross_final 3.5 15 3 1

; --- 5Aces_ ---
5Aces_paradise 3.5 15 3 1

; --- 5AM_ ---
5AM_DreamyWorld04 3.5 15 3 1

; --- alpin_ ---
alpin_beta01 3.5 15 3 1

; --- awp_ ---
awp_rooftops 3.5 15 3 1
awp_rooftops_new 3.5 15 3 1
awp_rooftops_remake 3.5 20 2 1
awp_rooftops_winter 3.5 20 3 1
crackhouse_beta02 3.5 15 3 1
; --- bOmji_ ---
bOmji_darktheme_final01 3.5 15 3 1
bOmji_nuke_final 3.5 15 3 1

; --- boost_ ---
boost_747_02 4.5 30 3 1
boost_uxata3 3.5 15 3 1
boost_gris 3.5 15 3 1
boost_aperture 3.5 15 3 1
boost_assault 4.5 30 3 1
boost_assault_am 4.5 30 3 1
boost_assault_fc 4.5 30 3 1
boost_assault_leo 4.5 30 3 1
boost_streetZ 3.5 30 3 1
boost_ayou 4.5 30 3 1
boost_aqueduct01 3.5 20 3 1
boost_brokentown 3.5 20 3 1
boost_brokentown_final 3.5 20 3 1
boost_cache 3.5 15 3 1
boost_cbble 3.5 15 3 1
boost_city 3.5 15 3 1
boost_cross2 3.5 15 3 1
boost_crossfire02 3.5 15 3 1
boost_cdust01 3.5 25 3 1
boost_deport_v129_v02.bsp 3.5 25 3 1
boost_darkalley01 3.5 15 3 1
boost_dust_flit 3.5 15 3 1
boost_edoc 3.5 15 3 1
boost_falldown_new 4.5 30 3 1
boost_floppytown_pro 4.0 25 3 1
boost_fookcity 3.5 20 3 1
boost_jumpers01 4.0 25 3 1
boost_junt 4.5 30 3 1
boost_ksworld 4.5 30 3 1 
boost_lapp 3.5 20 3 1
boost_mirage 3.5 15 3 1
boost_nmschool 4.5 30 3 1
boost_nuketown 3.5 15 3 1
boost_nuke 3.5 15 3 1
boost_newyear2024 4.5 30 3 1
boost_piranesi_03 3.5 15 3 1
boost_proworld01 3.5 15 3 1
boost_qube02 3.5 15 3 1
boost_remake2 4.5 30 3 1
boost_shizen_beta01 3.5 15 3 1
boost_sun 3.5 15 3 1
boost_sunset 3.5 15 3 1
boost_Skyscraper 4.5 30 3 1
boost_twintowers02 4.5 30 3 1
boost_town 4.5 30 3 1
boost_urban 3.5 15 3 1
boost_vertigo 3.5 15 3 1
boost_xanthi 3.5 15 3 1

; --- cs_ ---
cs_alpin 3.5 15 3 1

; --- dangerous_ ---
dangerous_assault 3.5 15 3 1
dangerous_brick_world2018 3.5 15 3 1

; --- de_ ---
de_barcelona 3.5 15 3 1
de_torn 3.5 15 3 1
de_torn_beta2 3.5 15 3 1
de_tuscan_boost_final 3.5 15 3 1
dangerous_mie 3.5 15 3 1


; --- hb_ ---
hb_garey 3.5 15 3 1

; --- hns_ ---
hns_2k12 3.5 15 3 1
hns_assault_crane 3.5 15 3 1
hns_bagdad 3.5 15 3 1
hns_boost_mirage 3.5 15 3 1
hns_boost_mirage_02 3.5 15 3 1
hns_dust2_boost 3.5 15 3 1
hns_funkytown 3.5 15 3 1
hns_inferno_boost 3.5 15 3 1
hns_inferno_boost_new 3.5 15 3 1
hns_mie 3.5 15 3 1
hns_mie2 3.5 15 3 1
hns_militia_boost 3.5 15 3 1
hns_neverland 3.5 15 3 1
hns_oldtown_boost 3.5 15 3 1
hns_piranesi_boost 4.0 15 1 1
hns_piranesi_classic 3.5 15 3 1
hns_poolday 3.5 15 3 1
hns_tolias 4.5 30 3 1
hns_ruins_boost 3.5 15 3 1
hns_shizen_beta010 3.5 15 3 1
hns_building_xnet 3.5 15 3 1
hns_virtual_boost 3.5 15 3 1
hnsboost_forge 3.5 15 3 1
hns_floppytown_pro 2.5 5 2 1

; --- hnscn_ ---
hnscn_assault 3.5 15 3 1
hnscn_italy 3.5 15 3 1

; --- hnsic_ ---
hnsic_floppytown01 3.5 20 3 1
hnsic_dust2 3.5 20 3 1

; --- hnsru_ ---
hnsru_assault01 3.5 15 3 1
hnsru_brick-world01 3.5 15 3 1
hnsru_cbble03 3.5 15 3 1
hnsru_chateau01a 3.5 15 3 1
hnsru_dust01 4.0 30 3 1
hnsru_floppytown01 3.5 15 3 1
hnsru_floppytown_mini 3.5 15 3 1
hnsru_inferno 3.5 15 3 1
hnsru_mie01 3.5 15 3 1
hnsru_militia01 3.5 15 3 1
hnsru_nuke 3.5 15 3 1
hnsru_nuke02 3.5 15 3 1
hnsru_nuke_boost_03 3.5 15 3 1
hnsru_overpass01a 3.5 15 3 1
hnsru_rooftops_mini 3.5 15 3 1
hnsru_susano_beta06 3.5 15 3 1
hnsru_train 3.5 15 3 1
hnsru_train01 3.5 15 3 1
hnsru_train_last 3.5 15 3 1
hnsru_sliders01 3.5 15 3 1
hnsro_village 3.5 15 3 1
; --- mini_ ---
mini_rooftops2 2.5 20 3 1

; --- office_ ---
office_beta02 3.5 15 3 1

; --- the_ ---
the_townsville 3.5 15 3 1

;----sk-----
shantaj_dock_alpha 4.0 25 3 1
shantaj_garden_f4 4.0 25 3 1
